<?php
$DEBUG = true;
$_SERVER['SERVER_ROOT'] = '/www2/';
$DEFAULTAREAID = 1;
$PAGEAFTERLOGGIN = 'company';
$NOTFOUNDPAGE = '404.php';
$DEMOCOMPANYID = 1;
$DEFAULTLOCALE = 'en_US';
$COUNTONPAGE = 5;
$TRANSLATEDOMAIN = 'lightmaster';
?>
